services:
  - type: worker
    name: twitter-news-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BEARER_TOKEN
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: ACCESS_SECRET
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false